GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Complete Assignment"
}

###

DELETE http://localhost:3001/todo/delete/65bbcadad34d93007b84275f

###

PUT http://localhost:3001/todo/complete/65b944a6bc7a4a12baf9dcb0